### ISSUE TITLE
Unable to use it

### ISSUE THREAD

**Issue by Sid281216** [intel/vscode-environment-variables#3]
Hi I’m trying to compile C++ and Fotran 77 code with intel oneapi(base+hpc) thanks to your extension in vscode but I don't understand how it works.. :
-I set up the ONEAPI env
-When I click generate tasks I get « choose target from cmake or press esc to exit »  here I don’t know what to do..I’m supposed to install  cmake ? I’ve already installed visual studio bluid tool 2019, selected « C++ Build tools » which include « C++ cmake tools for windows » 
Last question, I’m supposed to add some directories of oneapi to the windows PATH ?

I would really appreciate your help, you are workiing in a very promising project !
Best regards 
Mehdi

**Comment by amakarev** [comment]
Hi @Sid281216 
"Create task" is intended to create [a configuration file tasks.json](https://code.visualstudio.com/docs/editor/tasks), which would contain a command to build a project using cmake or make, depending on your project. Since you are prompted to select a target from cmake, I assume your project is based on cmake.

In case of a cmake project, two standard targets are offered - "all, clean", it also tries to find custom targets in CMakeLists.txt. You need cmake installed to work with this extension. I'm not sure about vs build tools, but you can try open a terminal in vscode after initializing oneapi environment and call "cmake --help" there. If the command works successfully, then no action on your part regarding the cmake is required. Otherwise, you need to install [cmake](https://cmake.org/), and make sure it's added to PATH.

> Last question, I’m supposed to add some directories of oneapi to the windows PATH ?

Nothing needs to be added manually. After executing the command "Intel oneAPI: Set oneAPI environment", the environment should be configured

**Comment by sbobko** [comment]
@Sid281216 I think the comment above is quite enough to close this problem, if you have any additional difficulties, please create a new one.
